# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-21 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20190720_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مقدار موجودی'),
        ),
    ]
