# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-01 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='کد رنگ'),
        ),
    ]
