# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-12 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_product_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='standard',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='استاندارد'),
        ),
    ]
